package Lab3;

import java.awt.Color;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

/**
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * <pre>
 * File         ShippingGUI.java
 * Project      Shipping Charges
 * Description  This class provide the GUI for Shipping Charges. A shipping
 *              Distribution Center uses this form to track parcel and charges
 *              applied for shipping the parcel.
 *
 * Platform     Mac, Big Sur 11.2.3, jdk 1.8.0_241, NetBeans IDE 12.3
 * Date         4/19/2021
 * History Log
 * @author      <i>Robert Tang</i>
 * @version     1.0.0
 * @see         javax.swing.JFrame
 * @see         java.awt.Toolkit
 * @see         java.awt.Color
 * </pre>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */
public class ShippingGUI extends javax.swing.JFrame {

    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method           Default constructor
     * Description      Creates new form ShippingGUI
     * @author          <i>Robert Tang</i>
     * Date             4/19/2021
     * </pre>
     *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    public ShippingGUI() {
        initComponents();

        // centers the form at start
        this.setLocationRelativeTo(null);

        // set course on periodicPaymentJFormattedTextField
        this.calculateJButton.requestFocus();

        // set default button on calculate
        this.getRootPane().setDefaultButton(calculateJButton);

        
        // set icon
        // There is a better way to set icon on the iconImage property, so commented out the 
        /// below line.
        // this.setIconImage(Toolkit.getDefaultToolkit().getImage("src/Lab3/parcel.png"));
        
        

        
        // change background color
        this.getContentPane().setBackground(new Color(186,143,177));

        // make jSpinners read-only 
        ((JSpinner.DefaultEditor) lbJSpinner.getEditor()).getTextField().setEditable(false);
        ((JSpinner.DefaultEditor) ozJSpinner.getEditor()).getTextField().setEditable(false);

        // set date on title bar
        this.setDate();
    }

    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method           setDate()
     * Description      Add date to the title bar.
     * @author          <i>Robert Tang</i>
     * Date             4/19/2021
     * </pre>
     *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void setDate() {
        DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
        Date now = new Date();
        this.setTitle("Shipping Application - " + dateFormat.format(now));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infoJPanel = new javax.swing.JPanel();
        idJLabel = new javax.swing.JLabel();
        idJFormattedTextField = new javax.swing.JFormattedTextField();
        weightJLabel = new javax.swing.JLabel();
        lbJSpinner = new javax.swing.JSpinner();
        lbJLabel = new javax.swing.JLabel();
        ozJSpinner = new javax.swing.JSpinner();
        ozJLabel = new javax.swing.JLabel();
        shippingJPanel = new javax.swing.JPanel();
        regionJLabel = new javax.swing.JLabel();
        regionJComboBox = new javax.swing.JComboBox<>();
        typeJLabel = new javax.swing.JLabel();
        typeJComboBox = new javax.swing.JComboBox<>();
        shippingJLabel = new javax.swing.JLabel();
        chargesJLabel = new javax.swing.JLabel();
        controlJPanel = new javax.swing.JPanel();
        calculateJButton = new javax.swing.JButton();
        clearJButton = new javax.swing.JButton();
        printJButton = new javax.swing.JButton();
        quitJButton = new javax.swing.JButton();
        shippingJMenuBar = new javax.swing.JMenuBar();
        fileJMenu = new javax.swing.JMenu();
        clearJMenuItem = new javax.swing.JMenuItem();
        printJMenuItem = new javax.swing.JMenuItem();
        quitJMenuItem = new javax.swing.JMenuItem();
        helpJMenu = new javax.swing.JMenu();
        aboutJMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Shipping Application");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Lab3/parcel.png")).getImage());
        setResizable(false);
        setSize(new java.awt.Dimension(733, 463));

        infoJPanel.setBackground(new java.awt.Color(186, 143, 177));
        infoJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Parcel Information"));

        idJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        idJLabel.setText("ID (6 digits):");

        try {
            idJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        idJFormattedTextField.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        weightJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        weightJLabel.setText("Weight:");

        lbJSpinner.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lbJSpinner.setModel(new javax.swing.SpinnerNumberModel(Byte.valueOf((byte)0), Byte.valueOf((byte)0), Byte.valueOf((byte)75), Byte.valueOf((byte)1)));
        lbJSpinner.setToolTipText("Maximum 75 pounds");

        lbJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lbJLabel.setText("lb.");

        ozJSpinner.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        ozJSpinner.setModel(new javax.swing.SpinnerNumberModel(Byte.valueOf((byte)0), Byte.valueOf((byte)0), Byte.valueOf((byte)15), Byte.valueOf((byte)1)));
        ozJSpinner.setToolTipText("Maximum 15 ounces");

        ozJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        ozJLabel.setText("oz.");

        javax.swing.GroupLayout infoJPanelLayout = new javax.swing.GroupLayout(infoJPanel);
        infoJPanel.setLayout(infoJPanelLayout);
        infoJPanelLayout.setHorizontalGroup(
            infoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoJPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(infoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idJLabel)
                    .addComponent(weightJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(infoJPanelLayout.createSequentialGroup()
                        .addComponent(lbJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ozJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(idJFormattedTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ozJLabel)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        infoJPanelLayout.setVerticalGroup(
            infoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoJPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(infoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idJLabel)
                    .addComponent(idJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbJLabel)
                        .addComponent(ozJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ozJLabel))
                    .addGroup(infoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(weightJLabel)
                        .addComponent(lbJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        shippingJPanel.setBackground(new java.awt.Color(186, 143, 177));
        shippingJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Shipping Information"));

        regionJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        regionJLabel.setText("Region:");

        regionJComboBox.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        regionJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));

        typeJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        typeJLabel.setText("Type:");

        typeJComboBox.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        typeJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ground", "Priority", "Express", "Next Day" }));
        typeJComboBox.setToolTipText("Priority $5 extra, Express $10 extra, Next Day $20 extra");

        javax.swing.GroupLayout shippingJPanelLayout = new javax.swing.GroupLayout(shippingJPanel);
        shippingJPanel.setLayout(shippingJPanelLayout);
        shippingJPanelLayout.setHorizontalGroup(
            shippingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shippingJPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(shippingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(regionJLabel)
                    .addComponent(typeJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(shippingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regionJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        shippingJPanelLayout.setVerticalGroup(
            shippingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shippingJPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(shippingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regionJLabel)
                    .addComponent(regionJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(shippingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeJLabel)
                    .addComponent(typeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        shippingJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        shippingJLabel.setText("Shipping Charges:");

        chargesJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        chargesJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chargesJLabel.setText("--");

        controlJPanel.setBackground(new java.awt.Color(186, 143, 177));
        controlJPanel.setLayout(new java.awt.GridLayout(1, 4, 3, 0));

        calculateJButton.setBackground(new java.awt.Color(255, 204, 204));
        calculateJButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        calculateJButton.setMnemonic('C');
        calculateJButton.setText("Calculate");
        calculateJButton.setToolTipText("");
        calculateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateJButtonActionPerformed(evt);
            }
        });
        controlJPanel.add(calculateJButton);

        clearJButton.setBackground(new java.awt.Color(255, 204, 204));
        clearJButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        clearJButton.setMnemonic('l');
        clearJButton.setText("Clear");
        clearJButton.setToolTipText("");
        clearJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJButtonActionPerformed(evt);
            }
        });
        controlJPanel.add(clearJButton);

        printJButton.setBackground(new java.awt.Color(255, 204, 204));
        printJButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        printJButton.setMnemonic('P');
        printJButton.setText("Print");
        printJButton.setToolTipText("");
        printJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printJButtonActionPerformed(evt);
            }
        });
        controlJPanel.add(printJButton);

        quitJButton.setBackground(new java.awt.Color(255, 204, 204));
        quitJButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        quitJButton.setMnemonic('Q');
        quitJButton.setText("Quit");
        quitJButton.setToolTipText("");
        quitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitJButtonActionPerformed(evt);
            }
        });
        controlJPanel.add(quitJButton);

        fileJMenu.setMnemonic('F');
        fileJMenu.setText("File");

        clearJMenuItem.setMnemonic('r');
        clearJMenuItem.setText("Clear");
        clearJMenuItem.setToolTipText("");
        clearJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJMenuItemActionPerformed(evt);
            }
        });
        fileJMenu.add(clearJMenuItem);

        printJMenuItem.setMnemonic('P');
        printJMenuItem.setText("Print");
        printJMenuItem.setToolTipText("Print form as GUI");
        printJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printJMenuItemActionPerformed(evt);
            }
        });
        fileJMenu.add(printJMenuItem);

        quitJMenuItem.setMnemonic('Q');
        quitJMenuItem.setText("Quit");
        quitJMenuItem.setToolTipText("Quit application");
        quitJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitJMenuItemActionPerformed(evt);
            }
        });
        fileJMenu.add(quitJMenuItem);

        shippingJMenuBar.add(fileJMenu);

        helpJMenu.setMnemonic('H');
        helpJMenu.setText("Help");

        aboutJMenuItem.setMnemonic('A');
        aboutJMenuItem.setText("About");
        aboutJMenuItem.setToolTipText("Show about form");
        aboutJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutJMenuItemActionPerformed(evt);
            }
        });
        helpJMenu.add(aboutJMenuItem);

        shippingJMenuBar.add(helpJMenu);

        setJMenuBar(shippingJMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(shippingJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chargesJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(controlJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(infoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(shippingJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shippingJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(infoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shippingJLabel)
                    .addComponent(chargesJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(controlJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method        quitJButtonActionPerformed()
     * Description   End the application
     * @param        java.awt.event.ActionEvent evt
     * @see java.awt.event.ActionEvent
     * @author       <i>Robert Tang</i>
     * Date 4/19/2021 History Log
     * </pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void quitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitJButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitJButtonActionPerformed

    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method        quitJMenuItemActionPerformed()
     * Description   End the application
     * @param        java.awt.event.ActionEvent evt
     * @see java.awt.event.ActionEvent
     * @author       <i>Robert Tang</i>
     * Date 4/19/2021 History Log
     * </pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void quitJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitJMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitJMenuItemActionPerformed

    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method        calculateJButtonActionPerformed()
     * Description   Calculates the shipping cost for a parcel.
     * @param        java.awt.event.ActionEvent evt
     * @see java.awt.event.ActionEvent
     * @author       <i>Robert Tang</i>
     * Date 4/19/2021 History Log
     * </pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void calculateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateJButtonActionPerformed
       
        try {
            // declaration of variables
            int id = 0;
            byte pounds = 0, ounces = 0, region = 1;
            double charges = 0.0, rate = 0;            
            String type = "Ground", idString = idJFormattedTextField.getText();
            DecimalFormat dollars = new DecimalFormat("$#,##0.00");
                       
            pounds = Byte.parseByte(lbJSpinner.getValue().toString());
            ounces = Byte.parseByte(ozJSpinner.getValue().toString());
            region = Byte.parseByte(regionJComboBox.getSelectedItem().toString());
            type = typeJComboBox.getSelectedItem().toString();
                       
            if (idString.length() != 6) {
                throw new NumberFormatException();
            }
            id = Integer.parseInt(idString);
            
            // instantiate a Parcel object
            Parcel instanceParcel = new Parcel(id, pounds, ounces, region, type);
            charges = instanceParcel.calculateCharges();
            
            //display charges
            chargesJLabel.setText(dollars.format(charges));
        } catch (NumberFormatException nexp) {
            System.err.println(nexp.toString());
            JOptionPane.showMessageDialog(this, "Must have 6 digits for ID SKU");
            idJFormattedTextField.requestFocus();
            idJFormattedTextField.selectAll();
        }
    }//GEN-LAST:event_calculateJButtonActionPerformed

    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method        printJButtonActionPerformed()
     * Description   Print form as GUI using PrintUtilities helper class.
     * @param        java.awt.event.ActionEvent evt
     * @see java.awt.event.ActionEvent
     * @author       <i>Robert Tang</i>
     * Date 4/19/2021 History Log
     * </pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void printJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printJButtonActionPerformed
        PrintUtilities.printComponent(this);
    }//GEN-LAST:event_printJButtonActionPerformed

    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method        printJMenuItemActionPerformed()
     * Description   Print form as GUI using PrintUtilities helper class.
     * @param        java.awt.event.ActionEvent evt
     * @see java.awt.event.ActionEvent
     * @author       <i>Robert Tang</i>
     * Date 4/19/2021 History Log
     * </pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void printJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printJMenuItemActionPerformed
        PrintUtilities.printComponent(this);
    }//GEN-LAST:event_printJMenuItemActionPerformed

    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method        clearJButtonActionPerformed()
     * Description   Clear all fields to default value.
     * @param        java.awt.event.ActionEvent evt
     * @see java.awt.event.ActionEvent
     * @author       <i>Robert Tang</i>
     * Date 4/19/2021 History Log
     * </pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void clearJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJButtonActionPerformed
        // clear all fields
        idJFormattedTextField.setValue("");
        lbJSpinner.setValue(0);
        ozJSpinner.setValue(0);
        regionJComboBox.setSelectedIndex(0);
        typeJComboBox.setSelectedIndex(0);
        chargesJLabel.setText("");

    }//GEN-LAST:event_clearJButtonActionPerformed

    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method        clearJMenuItemActionPerformed()
     * Description   Clear all fields to default value.
     * @param        java.awt.event.ActionEvent evt
     * @see java.awt.event.ActionEvent
     * @author       <i>Robert Tang</i>
     * Date 4/19/2021 History Log
     * </pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void clearJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJMenuItemActionPerformed
        clearJButton.doClick();
    }//GEN-LAST:event_clearJMenuItemActionPerformed

    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method        aboutJMenuItemActionPerformed()
     * Description   Displays the about form
     * @param        java.awt.event.ActionEvent evt
     * @author       <i>Robert Tang</i>
     * @see java.awt.event.ActionEvent
     * Date 4/19/2021 History Log
     * </pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void aboutJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutJMenuItemActionPerformed
        About instanceAbout = new About(this, true);
        instanceAbout.setVisible(true);
    }//GEN-LAST:event_aboutJMenuItemActionPerformed

    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method         main()
     * Description    Displays the main from of shipping charges.
     * @param         args are the command line strings
     * @author        <i>Robert Tang</i>
     * Date 4/19/2021
     * </pre>
     *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShippingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShippingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShippingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShippingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShippingGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutJMenuItem;
    private javax.swing.JButton calculateJButton;
    private javax.swing.JLabel chargesJLabel;
    private javax.swing.JButton clearJButton;
    private javax.swing.JMenuItem clearJMenuItem;
    private javax.swing.JPanel controlJPanel;
    private javax.swing.JMenu fileJMenu;
    private javax.swing.JMenu helpJMenu;
    private javax.swing.JFormattedTextField idJFormattedTextField;
    private javax.swing.JLabel idJLabel;
    private javax.swing.JPanel infoJPanel;
    private javax.swing.JLabel lbJLabel;
    private javax.swing.JSpinner lbJSpinner;
    private javax.swing.JLabel ozJLabel;
    private javax.swing.JSpinner ozJSpinner;
    private javax.swing.JButton printJButton;
    private javax.swing.JMenuItem printJMenuItem;
    private javax.swing.JButton quitJButton;
    private javax.swing.JMenuItem quitJMenuItem;
    private javax.swing.JComboBox<String> regionJComboBox;
    private javax.swing.JLabel regionJLabel;
    private javax.swing.JLabel shippingJLabel;
    private javax.swing.JMenuBar shippingJMenuBar;
    private javax.swing.JPanel shippingJPanel;
    private javax.swing.JComboBox<String> typeJComboBox;
    private javax.swing.JLabel typeJLabel;
    private javax.swing.JLabel weightJLabel;
    // End of variables declaration//GEN-END:variables
}
