
package Lab2;

import java.awt.Color;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;

/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*<pre>
* Class           LoanGUI
* File            LoanGUI.java
* Description     Calculate loan payment given loan amount, interest
*                 rate, and time of loan
* @author         <i>Robert Tang</i>
* Environment     Mac, Big Sure 11.2.3, jdk 1.8.0_241, NetBeans IDE 12.3
* Date            4/12/2021
* @version        1.0.0
* @see            javax.swing.JFrame
* History Log
*</pre>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
public class LoanGUI extends javax.swing.JFrame {

    int counter = 0; // number of calculations counter, class field.
    
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    * Method        LoanGUI() -- default constructor
    * Description   Creates new form LoanGUIs and displays it centered with icon
    *               and calculateJButton set as defaul, and also set background 
    *               color.
    * @author       <i>Robert Tang</i>
    * Date          4/12/2021
    *</pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    public LoanGUI() {
        initComponents(); // build the form
        
        // set calculateJButton as default
        this.getRootPane().setDefaultButton(calculateJButton);
        
        // set icon for form
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("src/Lab2/tennis.jpg"));
        
        // centers the form at start
        this.setLocationRelativeTo(null);
        
        // set cursor in principalJTextField
        this.principalJTextField.requestFocus();
        
        // change background color
        this.getContentPane().setBackground(Color.CYAN);
        
        this.setDate();
    }
    
    private void setDate(){
        DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
        Date now = new Date();
        this.setTitle("Loan Calculator -- " + dateFormat.format(now));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        counterJLabel = new javax.swing.JLabel();
        counterJTextField = new javax.swing.JTextField();
        principalJLabel = new javax.swing.JLabel();
        principalJTextField = new javax.swing.JTextField();
        rateJLabel = new javax.swing.JLabel();
        rateJTextField = new javax.swing.JTextField();
        yearsJLabel = new javax.swing.JLabel();
        yearsJTextField = new javax.swing.JTextField();
        calculateJButton = new javax.swing.JButton();
        paymentJTextField = new javax.swing.JTextField();
        interestJLabel = new javax.swing.JLabel();
        interestJTextField = new javax.swing.JTextField();
        clearJButton = new javax.swing.JButton();
        quitJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lab 2 - Loan Application");
        setMinimumSize(new java.awt.Dimension(500, 300));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(7, 2, 3, 3));

        counterJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        counterJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        counterJLabel.setText("Calculation Counter");
        counterJLabel.setToolTipText("");
        getContentPane().add(counterJLabel);

        counterJTextField.setEditable(false);
        counterJTextField.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        counterJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        counterJTextField.setEnabled(false);
        getContentPane().add(counterJTextField);

        principalJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        principalJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        principalJLabel.setText("Loan Amount");
        principalJLabel.setToolTipText("");
        getContentPane().add(principalJLabel);

        principalJTextField.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        principalJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(principalJTextField);

        rateJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        rateJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        rateJLabel.setText("Interest Rate (as %)");
        rateJLabel.setToolTipText("");
        getContentPane().add(rateJLabel);

        rateJTextField.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        rateJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(rateJTextField);

        yearsJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        yearsJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        yearsJLabel.setText("Years");
        yearsJLabel.setToolTipText("");
        getContentPane().add(yearsJLabel);

        yearsJTextField.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        yearsJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(yearsJTextField);

        calculateJButton.setBackground(new java.awt.Color(204, 255, 102));
        calculateJButton.setMnemonic('C');
        calculateJButton.setText("Calculate Payment");
        calculateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(calculateJButton);

        paymentJTextField.setEditable(false);
        paymentJTextField.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        paymentJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        paymentJTextField.setEnabled(false);
        getContentPane().add(paymentJTextField);

        interestJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        interestJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        interestJLabel.setText("Interest Paid");
        interestJLabel.setToolTipText("");
        getContentPane().add(interestJLabel);

        interestJTextField.setEditable(false);
        interestJTextField.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        interestJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        interestJTextField.setEnabled(false);
        getContentPane().add(interestJTextField);

        clearJButton.setBackground(new java.awt.Color(204, 255, 102));
        clearJButton.setMnemonic('r');
        clearJButton.setText("Clear");
        clearJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearJButton);

        quitJButton.setBackground(new java.awt.Color(204, 255, 102));
        quitJButton.setMnemonic('Q');
        quitJButton.setText("Quit");
        quitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(quitJButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    * Method        quitJButtonActionPerformed()
    * Description   End the application
    * @param        java.awt.event.ActionEvent evt
    * @see          java.awt.event.ActionEvent
    * @author       <i>Robert Tang</i>
    * Date          4/12/2021
    * History Log    
    *</pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/ 
    private void quitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitJButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitJButtonActionPerformed

    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    * Method        clearJButtonActionPerformed()
    * Description   Clear all input entries and outputs and reset form to 
    *               startup state
    * @param        java.awt.event.ActionEvent evt
    * @see          java.awt.event.ActionEvent
    * @author       <i>Robert Tang</i>
    * Date          4/12/2021
    * History Log    
    *</pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/ 
    private void clearJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJButtonActionPerformed
        counter = 0;
        counterJTextField.setText("");
        interestJTextField.setText("");
        paymentJTextField.setText("");
        principalJTextField.setText("");
        rateJTextField.setText("");
        yearsJTextField.setText("");
        principalJTextField.requestFocus();
    }//GEN-LAST:event_clearJButtonActionPerformed

    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    * Method        calculateJButtonActionPerformed()
    * Description   Calculate payment and interest paid on a loan given loan 
    *               amount, interest rate, and length of the loan in years, 
    *               all inputs from JTextFields
    * @param        java.awt.event.ActionEvent evt
    * @see          java.awt.event.ActionEvent
    * @see          java.text.DecimalFormat
    * @author       <i>Robert Tang</i>
    * Date          4/12/2021
    * History Log    
    *</pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/ 
    private void calculateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateJButtonActionPerformed
        // calculate payment on a loan.
        // constants for max values, and number of compoundings per year
        final double MAX_AMOUNT = 100000000;
        final double MAX_INTEREST_RATE = 100;
        final double COMPOUNDINGS = 12;
        final double PERIOD_INTEREST = COMPOUNDINGS * 100;
        
        String errorMessage = "Please enter a positive numbers for all required fields " + 
                "\nLoan amount must be in range (0, " + MAX_AMOUNT + "]" +
                "\nInterest rate must be in range [0, " + MAX_INTEREST_RATE + "]" + 
                "\nYears must be in range (0, " + MAX_INTEREST_RATE + "]";
        
        boolean invalidLoanAmount = true;
        boolean invalidRate = true;
        boolean invalidYears = true;
        
        try{
            // get inputs from textFields
            // invalidLoanAmount = true;
            double amount = Double.parseDouble(principalJTextField.getText());
            invalidLoanAmount  = amount <= 0 || amount > MAX_AMOUNT;

            //invalidRace = true;
            double rate = Double.parseDouble(rateJTextField.getText());
            invalidRate = rate < 0 || rate > MAX_INTEREST_RATE;


            //invalidYears = true;
            double years = Double.parseDouble(yearsJTextField.getText());
            invalidYears = years < 0 || years > 100;

            
            boolean invalidlnputs = invalidLoanAmount || invalidRate || invalidYears;
            
            if (invalidlnputs)
                throw new NumberFormatException();
            else{
                //calculace paymenc using formula
                counter++;
                double payment = (amount * rate/PERIOD_INTEREST) 
                                 / (1 - Math.pow((1 + rate/PERIOD_INTEREST), years * (-COMPOUNDINGS)));
                
                double interest = years * COMPOUNDINGS * payment - amount;
                DecimalFormat dollars = new DecimalFormat("$#,##0.00");
                String result = dollars.format(payment);
                
                
                // Display results
                counterJTextField.setText(String.valueOf(counter));
                paymentJTextField.setText(result);
                interestJTextField.setText(dollars.format(interest));
            }
            
        }
        catch(NumberFormatException nume)
        {
            JOptionPane.showMessageDialog(null, errorMessage,
            "Input Error", JOptionPane.WARNING_MESSAGE);
            
            if(invalidLoanAmount){
                principalJTextField.requestFocus();
                principalJTextField.selectAll();
            }
            else if(invalidRate){
                rateJTextField.requestFocus();
                rateJTextField.selectAll();
            }
            else if(invalidYears){
                yearsJTextField.requestFocus();
                yearsJTextField.selectAll();
            }
            
        }
    }//GEN-LAST:event_calculateJButtonActionPerformed
    
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    * Method        main()
    * Description   Displays 4 digits and accesses command-line arguments
    * @param        args the command line arguments
    * @author       <i>Robert Tang</i>
    * Date          4/12/2021
    * History Log    
    *</pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/ 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateJButton;
    private javax.swing.JButton clearJButton;
    private javax.swing.JLabel counterJLabel;
    private javax.swing.JTextField counterJTextField;
    private javax.swing.JLabel interestJLabel;
    private javax.swing.JTextField interestJTextField;
    private javax.swing.JTextField paymentJTextField;
    private javax.swing.JLabel principalJLabel;
    private javax.swing.JTextField principalJTextField;
    private javax.swing.JButton quitJButton;
    private javax.swing.JLabel rateJLabel;
    private javax.swing.JTextField rateJTextField;
    private javax.swing.JLabel yearsJLabel;
    private javax.swing.JTextField yearsJTextField;
    // End of variables declaration//GEN-END:variables
}
