package Lab1;

import java.awt.Toolkit;
import java.text.DecimalFormat;

/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*<pre>
* File         OhmsLawGUI.java
* Project      Ohm's Law
* Description  This class provide the GUI for Ohm�s Law formula. In electrical
*              circuits, Ohm's law states that the current through a conductor
*              between two points is directly proportional to the potential
*              difference or voltage across the two points, and inversely
*              proportional to the resistance between them, provided that the
*              temperature remains constant. The mathematical equation that
*              describes this relationship is: * I = V/R  or R = V/I  or
*              V = I * R, where V is the potential difference measured across
*              the resistance in units of volts; I is the current through the
*              resistance in units of amperes and R is the resistance of the
*              conductor in units of ohms. More specifically, Ohm's law states
*              that the R in this relation is constant, independent of the
*              current.
*              The law was named after the German physicist Georg Ohm, who, in
*              a treatise published in 1827, described measurements of applied
*              voltage and current through simple electrical circuits containing
*              various lengths of wire. He presented a slightly more complex
*              equation than the one above to explain his experimental results.
*              The above equation is the modern form of Ohm's law.
*
* Platform     jdk 1.8.0_241, NetBeans IDE 12.3,  Mac 11.2.3
* Hours        2 hours and 45 minutes
* Date         4/3/2021
* History Log  
* @author      <i>Robert Tang</i>
* @version     %1% %2%
* @see         javax.swing.JFrame
* @see         java.awt.Toolkit
* @see         java.awt.Color
*</pre>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
public class OhmsLawGUI extends javax.swing.JFrame {

    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    * Constructor   OhmsLawGUI()
    * Description   Creates the OhmsLawGUI form, centers it, sets the 
    *               calculateJButton as default, set some background color.
    * @author       <i>Robert Tang</i>      
    * Date          4/2/2021
    * History Log   4/2/2009, 11/6/2013, 7/18/2018
    *</pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    public OhmsLawGUI() 
    {
        initComponents(); // form is created here
        // set button calculateJButton as default
        this.getRootPane().setDefaultButton(calculateJButton);
        // set icon for form 
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("src/Lab1/ohmsFormula.jpg"));
        // center form
        this.setLocationRelativeTo(null);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleJLabel = new javax.swing.JLabel();
        vJLabel = new javax.swing.JLabel();
        voltsJTextField = new javax.swing.JTextField();
        voltsJLabel = new javax.swing.JLabel();
        resistanceJTextField = new javax.swing.JTextField();
        rJLabel = new javax.swing.JLabel();
        ohmsJLabel = new javax.swing.JLabel();
        rJLabel1 = new javax.swing.JLabel();
        currentJTextField = new javax.swing.JTextField();
        ohmsJLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        calculateJButton = new javax.swing.JButton();
        clearJButton = new javax.swing.JButton();
        printJButton = new javax.swing.JButton();
        quitJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lab 1 - Ohm's Law");
        setBackground(new java.awt.Color(204, 255, 204));
        setResizable(false);

        titleJLabel.setFont(new java.awt.Font("Lucida Grande", 2, 24)); // NOI18N
        titleJLabel.setForeground(new java.awt.Color(102, 0, 0));
        titleJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lab1/OhmsFormula.jpg"))); // NOI18N
        titleJLabel.setText("Ohm's Law");
        titleJLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        vJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        vJLabel.setText("V:");

        voltsJTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        voltsJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        voltsJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        voltsJLabel.setText("volts");

        resistanceJTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        resistanceJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        rJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        rJLabel.setText("R:");

        ohmsJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        ohmsJLabel.setText("ohms");

        rJLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        rJLabel1.setText("I:");

        currentJTextField.setEditable(false);
        currentJTextField.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        currentJTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        ohmsJLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        ohmsJLabel1.setText("amperes");

        jPanel1.setLayout(new java.awt.GridLayout(2, 2, 3, 3));

        calculateJButton.setBackground(new java.awt.Color(204, 255, 204));
        calculateJButton.setMnemonic('C');
        calculateJButton.setText("Calculate");
        calculateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(calculateJButton);

        clearJButton.setBackground(new java.awt.Color(204, 255, 204));
        clearJButton.setMnemonic('r');
        clearJButton.setText("Clear");
        clearJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(clearJButton);

        printJButton.setBackground(new java.awt.Color(204, 255, 204));
        printJButton.setMnemonic('P');
        printJButton.setText("Print");
        printJButton.setEnabled(false);
        jPanel1.add(printJButton);

        quitJButton.setBackground(new java.awt.Color(204, 255, 204));
        quitJButton.setMnemonic('Q');
        quitJButton.setText("Quit");
        quitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitJButtonActionPerformed(evt);
            }
        });
        jPanel1.add(quitJButton);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rJLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(currentJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ohmsJLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resistanceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ohmsJLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(titleJLabel)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(vJLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(voltsJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(voltsJLabel)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vJLabel)
                    .addComponent(voltsJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltsJLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rJLabel)
                    .addComponent(resistanceJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ohmsJLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rJLabel1)
                    .addComponent(currentJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ohmsJLabel1))
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    * Method        quitJButtonActionPerformed()
    * Description   Quit the application.
    * Date          4/2/2021
    * @author       <i>Robert Tang</i>
    * @param        evt java.awt.event.ActionEvent
    * @see          java.awt.event.ActionEvent
    *</pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void quitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitJButtonActionPerformed
        // Terminate the application
        System.exit(0);
    }//GEN-LAST:event_quitJButtonActionPerformed

    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    * Method        clearJButtonActionPerformed()
    * Description   Clears the form and resets it to its original state.
    * Date          4/2/2021
    * @author       <i>Robert Tang</i>
    * @param        evt java.awt.event.ActionEvent
    * @see 		java.text.DecimalFormat
    *</pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void clearJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJButtonActionPerformed
        // Clear all text fields and reset the form
        currentJTextField.setText("");
        resistanceJTextField.setText("");
        voltsJTextField.setText("");
        voltsJTextField.requestFocus();
    }//GEN-LAST:event_clearJButtonActionPerformed
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    * Method        calculateJButtonActionPerformed()
    * Description   Calculates current through a conductor between two points
    *               given the voltage across the two points, and resistance
    *               between them.
    * Date          4/2/2021
    * @author       <i>Robert Tang</i>
    * @param        evt java.awt.event.ActionEvent
    * @see          java.awt.event.ActionEvent
    * @see          java.text.DecimalFormat
    *</pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void calculateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateJButtonActionPerformed
        // Calculate the current given voltage and resistance
        DecimalFormat twoDecimals = new DecimalFormat("#,##0.00");
        float volts, resistance, current;
        volts = Float.parseFloat(voltsJTextField.getText());
        resistance = Float.parseFloat(resistanceJTextField.getText());
        current = volts / resistance;
        currentJTextField.setText(twoDecimals.format(current));
    }//GEN-LAST:event_calculateJButtonActionPerformed

    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    * Method        main()
    * Description   Creates and sets visible and instance of the OhmsLawGUI.
    * Date          4/2/2021
    * History Log   4/2/2009, 11/6/2013, 7/18/2018
    * @author       <i>Robert Tang</i>
    * @param        args String[]
    *</pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OhmsLawGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OhmsLawGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OhmsLawGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OhmsLawGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OhmsLawGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateJButton;
    private javax.swing.JButton clearJButton;
    private javax.swing.JTextField currentJTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel ohmsJLabel;
    private javax.swing.JLabel ohmsJLabel1;
    private javax.swing.JButton printJButton;
    private javax.swing.JButton quitJButton;
    private javax.swing.JLabel rJLabel;
    private javax.swing.JLabel rJLabel1;
    private javax.swing.JTextField resistanceJTextField;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JLabel vJLabel;
    private javax.swing.JLabel voltsJLabel;
    private javax.swing.JTextField voltsJTextField;
    // End of variables declaration//GEN-END:variables
}
