/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab6;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.print.PrinterException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * <pre>
 * File         GeometriesGUI.java
 * Project      Lab6
 * Description  This class provides the main GUI for geometiry calculations of 
 *              triangles. It allows user to enter 3 vertices of a triangle, and 
 *              computes the perimeter, area, and test wether it's a valid triangle
 *              and testing wether a point is inside that triangle.
 * Platform     Mac, Big Sur 11.2.3, jdk 1.8.0_241, NetBeans IDE 12.3
 * Date         5/15/2021
 * History Log
 * @author      <i>Robert Tang</i>
 * @version 1.0.0
 * </pre>
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */
public class GeometriesGUI extends javax.swing.JFrame {

    DecimalFormat numFormat = new DecimalFormat("#,##0.00");


    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method           WaterBillDriver()
     * Description      Creates new form of GeometriesGUI.
     * Date 5/15/2021
     * @author          <i>Robert Tang</i>
     * </pre>
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    public GeometriesGUI() {
        initComponents();

        // centers the form at start
        this.setLocationRelativeTo(null);

        // set date on title bar
        this.setDate();
    }

    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method           setDate()
     * Description      Set current date the title bar.
     * @author          <i>Robert Tang</i>
     * Date 5/15/2021
     * </pre>
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void setDate() {
        Date now = new Date();
        DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
        this.setTitle("Geometries Calculations - " + dateFormat.format(now));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        geometriesJTabbedPane = new javax.swing.JTabbedPane();
        mainJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        figureJComboBox = new javax.swing.JComboBox<>();
        triangleJLabel = new javax.swing.JLabel();
        rightTriangleJLabel = new javax.swing.JLabel();
        anyTriangleJLabel = new javax.swing.JLabel();
        mercatorSeriesJLabel = new javax.swing.JLabel();
        calculationJPanel = new javax.swing.JPanel();
        verticesJPanel = new javax.swing.JPanel();
        x1JLabel = new javax.swing.JLabel();
        x1JFormattedTextField = new javax.swing.JFormattedTextField();
        y1JLabel = new javax.swing.JLabel();
        y1JFormattedTextField = new javax.swing.JFormattedTextField();
        x2JLabel = new javax.swing.JLabel();
        x2JFormattedTextField = new javax.swing.JFormattedTextField();
        y2JLabel = new javax.swing.JLabel();
        y2JFormattedTextField = new javax.swing.JFormattedTextField();
        x3JLabel = new javax.swing.JLabel();
        x3JFormattedTextField = new javax.swing.JFormattedTextField();
        y3JLabel = new javax.swing.JLabel();
        y3JFormattedTextField = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descTriangleJTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        resultJTextArea = new javax.swing.JTextArea();
        triangleJButton = new javax.swing.JButton();
        rightTriangleJPanel = new javax.swing.JPanel();
        pointsJPanel = new javax.swing.JPanel();
        bJLabel = new javax.swing.JLabel();
        bJFormattedTextField = new javax.swing.JFormattedTextField();
        cJLabel = new javax.swing.JLabel();
        cJFormattedTextField = new javax.swing.JFormattedTextField();
        xValueJLabel = new javax.swing.JLabel();
        xValueJFormattedTextField = new javax.swing.JFormattedTextField();
        yValueJLabel = new javax.swing.JLabel();
        yValueJFormattedTextField = new javax.swing.JFormattedTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        descRightTriangleJTextArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        resultRightTriangleJTextArea = new javax.swing.JTextArea();
        rightTriJButton = new javax.swing.JButton();
        anyTriangleJPanel = new javax.swing.JPanel();
        verticesJPanel2 = new javax.swing.JPanel();
        x1AnyJLabel = new javax.swing.JLabel();
        x1AnyJFormattedTextField = new javax.swing.JFormattedTextField();
        y1AnyJLabel = new javax.swing.JLabel();
        y1AnyJFormattedTextField = new javax.swing.JFormattedTextField();
        x2AnyJLabel = new javax.swing.JLabel();
        x2AnyJFormattedTextField = new javax.swing.JFormattedTextField();
        y2AnyJLabel = new javax.swing.JLabel();
        y2AnyJFormattedTextField = new javax.swing.JFormattedTextField();
        x3AnyJLabel = new javax.swing.JLabel();
        x3AnyJFormattedTextField = new javax.swing.JFormattedTextField();
        y3AnyJLabel = new javax.swing.JLabel();
        y3AnyJFormattedTextField = new javax.swing.JFormattedTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        descAnyTriJTextArea = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        resultOfAnyTriangleJTextArea = new javax.swing.JTextArea();
        anyTriangleJButton = new javax.swing.JButton();
        x1JLabel4 = new javax.swing.JLabel();
        y1JLabel4 = new javax.swing.JLabel();
        x1TestAnyTriangleJFormattedTextField = new javax.swing.JFormattedTextField();
        y1TestAnyTriangleJFormattedTextField = new javax.swing.JFormattedTextField();
        mercatorSeriesJPanel = new javax.swing.JPanel();
        verticesJPanel3 = new javax.swing.JPanel();
        numbersOfTermsJLabel = new javax.swing.JLabel();
        numberOfTermsJFormattedTextField = new javax.swing.JFormattedTextField();
        value4xJLabel = new javax.swing.JLabel();
        value4xJFormattedTextField = new javax.swing.JFormattedTextField();
        mercatorJButton = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        descMercatorJTextArea = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        resultOfMecatorJTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        lab6JMenuBar = new javax.swing.JMenuBar();
        fileJMenu = new javax.swing.JMenu();
        clearJMenuItem = new javax.swing.JMenuItem();
        printJMenuItem = new javax.swing.JMenuItem();
        printFormJMenuItem = new javax.swing.JMenuItem();
        exitJMenuItem = new javax.swing.JMenuItem();
        panelJMenu = new javax.swing.JMenu();
        mainJMenuItem = new javax.swing.JMenuItem();
        triangleJMenuItem = new javax.swing.JMenuItem();
        rightTriangleJMenuItem = new javax.swing.JMenuItem();
        anyTriangleJMenuItem = new javax.swing.JMenuItem();
        mercatorSeriesJMenuItem = new javax.swing.JMenuItem();
        helpJMenu = new javax.swing.JMenu();
        aboutJMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Images/PI.jpg")).getImage());
        setResizable(false);

        mainJPanel.setBackground(new java.awt.Color(255, 255, 202));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 2, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(159, 3, 48));
        jLabel1.setText("Welcome to Triangle Calculations");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("Select geometric figure:");

        figureJComboBox.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        figureJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<select>", "Triangle Calculations", "Point in a Right Triangle", "Point in any Triangle", "Mercator Series" }));
        figureJComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                figureJComboBoxItemStateChanged(evt);
            }
        });

        triangleJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Scalene.png"))); // NOI18N
        triangleJLabel.setToolTipText("Click on point inside any fiture opens correspending Panel.");
        triangleJLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        triangleJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                triangleJLabelMouseClicked(evt);
            }
        });

        rightTriangleJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Point in Right Triangle.png"))); // NOI18N
        rightTriangleJLabel.setToolTipText("Click on point inside any fiture opens correspending Panel.");
        rightTriangleJLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rightTriangleJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rightTriangleJLabelMouseClicked(evt);
            }
        });

        anyTriangleJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Point in Any Triangle.png"))); // NOI18N
        anyTriangleJLabel.setToolTipText("Click on point inside any fiture opens correspending Panel.");
        anyTriangleJLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anyTriangleJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anyTriangleJLabelMouseClicked(evt);
            }
        });

        mercatorSeriesJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Mercator Series.png"))); // NOI18N
        mercatorSeriesJLabel.setToolTipText("Click on point inside any fiture opens correspending Panel.");
        mercatorSeriesJLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mercatorSeriesJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mercatorSeriesJLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mainJPanelLayout = new javax.swing.GroupLayout(mainJPanel);
        mainJPanel.setLayout(mainJPanelLayout);
        mainJPanelLayout.setHorizontalGroup(
            mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainJPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(triangleJLabel)
                .addGap(28, 28, 28)
                .addComponent(rightTriangleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(anyTriangleJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
            .addGroup(mainJPanelLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(mercatorSeriesJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(figureJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(78, 78, 78))
        );
        mainJPanelLayout.setVerticalGroup(
            mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainJPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(figureJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(38, 38, 38)
                .addGroup(mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anyTriangleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(triangleJLabel)
                    .addComponent(rightTriangleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mercatorSeriesJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        geometriesJTabbedPane.addTab("Main Panel", mainJPanel);

        calculationJPanel.setBackground(new java.awt.Color(191, 255, 201));
        calculationJPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                calculationJPanelComponentShown(evt);
            }
        });

        verticesJPanel.setBackground(new java.awt.Color(191, 255, 201));
        verticesJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Vertices"));
        verticesJPanel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        verticesJPanel.setLayout(new java.awt.GridLayout(3, 4, 3, 3));

        x1JLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        x1JLabel.setText("x1");
        verticesJPanel.add(x1JLabel);

        x1JFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        verticesJPanel.add(x1JFormattedTextField);

        y1JLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        y1JLabel.setText("y1");
        verticesJPanel.add(y1JLabel);

        y1JFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        verticesJPanel.add(y1JFormattedTextField);

        x2JLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        x2JLabel.setText("x2");
        verticesJPanel.add(x2JLabel);

        x2JFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        verticesJPanel.add(x2JFormattedTextField);

        y2JLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        y2JLabel.setText("y2");
        verticesJPanel.add(y2JLabel);

        y2JFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        verticesJPanel.add(y2JFormattedTextField);

        x3JLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        x3JLabel.setText("x3");
        verticesJPanel.add(x3JLabel);

        x3JFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        verticesJPanel.add(x3JFormattedTextField);

        y3JLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        y3JLabel.setText("y3");
        y3JLabel.setToolTipText("");
        verticesJPanel.add(y3JLabel);

        y3JFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        verticesJPanel.add(y3JFormattedTextField);

        descTriangleJTextArea.setEditable(false);
        descTriangleJTextArea.setColumns(20);
        descTriangleJTextArea.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        descTriangleJTextArea.setLineWrap(true);
        descTriangleJTextArea.setRows(1);
        descTriangleJTextArea.setTabSize(1);
        descTriangleJTextArea.setText("Enter three vertices for a triangle to compute the perimeter and the area if the input is valid. Otherwise, display that the input is invalid. The input is valid if the sum of every pair of two edges is greater than the remaining edge.");
        descTriangleJTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(descTriangleJTextArea);

        resultJTextArea.setEditable(false);
        resultJTextArea.setColumns(20);
        resultJTextArea.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        resultJTextArea.setLineWrap(true);
        resultJTextArea.setRows(1);
        resultJTextArea.setTabSize(1);
        resultJTextArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(resultJTextArea);

        triangleJButton.setBackground(new java.awt.Color(255, 255, 255));
        triangleJButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        triangleJButton.setMnemonic('C');
        triangleJButton.setText("Calculate");
        triangleJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                triangleJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout calculationJPanelLayout = new javax.swing.GroupLayout(calculationJPanel);
        calculationJPanel.setLayout(calculationJPanelLayout);
        calculationJPanelLayout.setHorizontalGroup(
            calculationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calculationJPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(calculationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(verticesJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                .addGroup(calculationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(calculationJPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(triangleJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(calculationJPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        calculationJPanelLayout.setVerticalGroup(
            calculationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calculationJPanelLayout.createSequentialGroup()
                .addGroup(calculationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(calculationJPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(triangleJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(calculationJPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(verticesJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(calculationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        geometriesJTabbedPane.addTab("Triangle Calculations", calculationJPanel);

        rightTriangleJPanel.setBackground(new java.awt.Color(255, 204, 204));
        rightTriangleJPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                rightTriangleJPanelComponentShown(evt);
            }
        });

        pointsJPanel.setBackground(new java.awt.Color(255, 204, 204));
        pointsJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Points"));
        pointsJPanel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        pointsJPanel.setLayout(new java.awt.GridLayout(2, 4, 3, 3));

        bJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        bJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bJLabel.setText("b:");
        pointsJPanel.add(bJLabel);

        bJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        pointsJPanel.add(bJFormattedTextField);

        cJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cJLabel.setText("c:");
        pointsJPanel.add(cJLabel);

        cJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        pointsJPanel.add(cJFormattedTextField);

        xValueJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        xValueJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xValueJLabel.setText("x:");
        pointsJPanel.add(xValueJLabel);

        xValueJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        pointsJPanel.add(xValueJFormattedTextField);

        yValueJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        yValueJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        yValueJLabel.setText("y:");
        pointsJPanel.add(yValueJLabel);

        yValueJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        pointsJPanel.add(yValueJFormattedTextField);

        descRightTriangleJTextArea.setEditable(false);
        descRightTriangleJTextArea.setColumns(20);
        descRightTriangleJTextArea.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        descRightTriangleJTextArea.setLineWrap(true);
        descRightTriangleJTextArea.setRows(1);
        descRightTriangleJTextArea.setTabSize(1);
        descRightTriangleJTextArea.setText("Suppose a right triangle is placed in a plane with one vertex at (0,0), the right-angle point, and the other two points are placed at (c, 0), and (0, b). Enter the values for b and c as well as the point with x- and y-coordinates to determines whether the point is inside the triangle.");
        descRightTriangleJTextArea.setWrapStyleWord(true);
        jScrollPane3.setViewportView(descRightTriangleJTextArea);

        resultRightTriangleJTextArea.setEditable(false);
        resultRightTriangleJTextArea.setColumns(20);
        resultRightTriangleJTextArea.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        resultRightTriangleJTextArea.setLineWrap(true);
        resultRightTriangleJTextArea.setRows(1);
        resultRightTriangleJTextArea.setTabSize(1);
        resultRightTriangleJTextArea.setWrapStyleWord(true);
        jScrollPane4.setViewportView(resultRightTriangleJTextArea);

        rightTriJButton.setBackground(new java.awt.Color(255, 255, 255));
        rightTriJButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        rightTriJButton.setMnemonic('C');
        rightTriJButton.setText("Calculate");
        rightTriJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightTriJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightTriangleJPanelLayout = new javax.swing.GroupLayout(rightTriangleJPanel);
        rightTriangleJPanel.setLayout(rightTriangleJPanelLayout);
        rightTriangleJPanelLayout.setHorizontalGroup(
            rightTriangleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightTriangleJPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(rightTriangleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pointsJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                .addGroup(rightTriangleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightTriangleJPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(rightTriJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rightTriangleJPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        rightTriangleJPanelLayout.setVerticalGroup(
            rightTriangleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightTriangleJPanelLayout.createSequentialGroup()
                .addGroup(rightTriangleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightTriangleJPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(pointsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rightTriangleJPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(rightTriJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(rightTriangleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        geometriesJTabbedPane.addTab("Right Triangle", rightTriangleJPanel);

        anyTriangleJPanel.setBackground(new java.awt.Color(204, 204, 255));
        anyTriangleJPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                anyTriangleJPanelComponentShown(evt);
            }
        });

        verticesJPanel2.setBackground(new java.awt.Color(204, 204, 255));
        verticesJPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vertices", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 14))); // NOI18N
        verticesJPanel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        verticesJPanel2.setLayout(new java.awt.GridLayout(3, 4, 3, 3));

        x1AnyJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        x1AnyJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        x1AnyJLabel.setText("x1");
        verticesJPanel2.add(x1AnyJLabel);

        x1AnyJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        verticesJPanel2.add(x1AnyJFormattedTextField);

        y1AnyJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        y1AnyJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        y1AnyJLabel.setText("y1");
        verticesJPanel2.add(y1AnyJLabel);

        y1AnyJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        verticesJPanel2.add(y1AnyJFormattedTextField);

        x2AnyJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        x2AnyJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        x2AnyJLabel.setText("x2");
        verticesJPanel2.add(x2AnyJLabel);

        x2AnyJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        verticesJPanel2.add(x2AnyJFormattedTextField);

        y2AnyJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        y2AnyJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        y2AnyJLabel.setText("y2");
        verticesJPanel2.add(y2AnyJLabel);

        y2AnyJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        verticesJPanel2.add(y2AnyJFormattedTextField);

        x3AnyJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        x3AnyJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        x3AnyJLabel.setText("x3");
        verticesJPanel2.add(x3AnyJLabel);

        x3AnyJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        verticesJPanel2.add(x3AnyJFormattedTextField);

        y3AnyJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        y3AnyJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        y3AnyJLabel.setText("y3");
        y3AnyJLabel.setToolTipText("");
        verticesJPanel2.add(y3AnyJLabel);

        y3AnyJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        verticesJPanel2.add(y3AnyJFormattedTextField);

        descAnyTriJTextArea.setEditable(false);
        descAnyTriJTextArea.setColumns(20);
        descAnyTriJTextArea.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        descAnyTriJTextArea.setLineWrap(true);
        descAnyTriJTextArea.setRows(1);
        descAnyTriJTextArea.setTabSize(1);
        descAnyTriJTextArea.setText("Enter three vertices for a triangle and a test point to determine if the point is inside or outside of the triangle. Must check first for valid triangle: sum of any two edges is greater than the third.");
        descAnyTriJTextArea.setWrapStyleWord(true);
        jScrollPane5.setViewportView(descAnyTriJTextArea);

        resultOfAnyTriangleJTextArea.setEditable(false);
        resultOfAnyTriangleJTextArea.setColumns(20);
        resultOfAnyTriangleJTextArea.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        resultOfAnyTriangleJTextArea.setLineWrap(true);
        resultOfAnyTriangleJTextArea.setRows(1);
        resultOfAnyTriangleJTextArea.setTabSize(1);
        resultOfAnyTriangleJTextArea.setWrapStyleWord(true);
        jScrollPane6.setViewportView(resultOfAnyTriangleJTextArea);

        anyTriangleJButton.setBackground(new java.awt.Color(255, 255, 255));
        anyTriangleJButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        anyTriangleJButton.setMnemonic('C');
        anyTriangleJButton.setText("Calculate");
        anyTriangleJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anyTriangleJButtonActionPerformed(evt);
            }
        });

        x1JLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        x1JLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        x1JLabel4.setText("Test point:  x");

        y1JLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        y1JLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        y1JLabel4.setText("y");

        x1TestAnyTriangleJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        y1TestAnyTriangleJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout anyTriangleJPanelLayout = new javax.swing.GroupLayout(anyTriangleJPanel);
        anyTriangleJPanel.setLayout(anyTriangleJPanelLayout);
        anyTriangleJPanelLayout.setHorizontalGroup(
            anyTriangleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anyTriangleJPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(anyTriangleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(verticesJPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                .addGap(51, 51, 51)
                .addGroup(anyTriangleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(anyTriangleJPanelLayout.createSequentialGroup()
                        .addGroup(anyTriangleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                            .addComponent(anyTriangleJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31))
                    .addGroup(anyTriangleJPanelLayout.createSequentialGroup()
                        .addComponent(x1JLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x1TestAnyTriangleJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(y1JLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(y1TestAnyTriangleJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        anyTriangleJPanelLayout.setVerticalGroup(
            anyTriangleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anyTriangleJPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(anyTriangleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(anyTriangleJPanelLayout.createSequentialGroup()
                        .addGroup(anyTriangleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(x1JLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(anyTriangleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(y1JLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(x1TestAnyTriangleJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(y1TestAnyTriangleJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anyTriangleJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(verticesJPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(anyTriangleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(jScrollPane6))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        geometriesJTabbedPane.addTab("Any Triangle", anyTriangleJPanel);

        mercatorSeriesJPanel.setBackground(new java.awt.Color(255, 204, 0));
        mercatorSeriesJPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                mercatorSeriesJPanelComponentShown(evt);
            }
        });

        verticesJPanel3.setBackground(new java.awt.Color(255, 204, 0));
        verticesJPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inputs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 14))); // NOI18N
        verticesJPanel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N

        numbersOfTermsJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        numbersOfTermsJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        numbersOfTermsJLabel.setText("Numbers of terms:");

        numberOfTermsJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#"))));
        numberOfTermsJFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        value4xJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        value4xJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        value4xJLabel.setText("Value for x:");

        value4xJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        mercatorJButton.setBackground(new java.awt.Color(255, 255, 255));
        mercatorJButton.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        mercatorJButton.setMnemonic('C');
        mercatorJButton.setText("Calculate");
        mercatorJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mercatorJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout verticesJPanel3Layout = new javax.swing.GroupLayout(verticesJPanel3);
        verticesJPanel3.setLayout(verticesJPanel3Layout);
        verticesJPanel3Layout.setHorizontalGroup(
            verticesJPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verticesJPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(verticesJPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numbersOfTermsJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(verticesJPanel3Layout.createSequentialGroup()
                        .addComponent(value4xJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(value4xJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(numberOfTermsJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(mercatorJButton)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        verticesJPanel3Layout.setVerticalGroup(
            verticesJPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verticesJPanel3Layout.createSequentialGroup()
                .addGroup(verticesJPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(verticesJPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(numbersOfTermsJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numberOfTermsJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(verticesJPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(value4xJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(value4xJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(verticesJPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(mercatorJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        descMercatorJTextArea.setEditable(false);
        descMercatorJTextArea.setColumns(20);
        descMercatorJTextArea.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        descMercatorJTextArea.setLineWrap(true);
        descMercatorJTextArea.setRows(1);
        descMercatorJTextArea.setTabSize(1);
        descMercatorJTextArea.setText("Enter number of terms to be summed for the Mercator series, and argument. Results will show sum, time to complete the summation, and relative error from exact value. For large number of terms keep value of x very close to 1.");
        descMercatorJTextArea.setWrapStyleWord(true);
        jScrollPane7.setViewportView(descMercatorJTextArea);

        resultOfMecatorJTextArea.setEditable(false);
        resultOfMecatorJTextArea.setColumns(20);
        resultOfMecatorJTextArea.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        resultOfMecatorJTextArea.setLineWrap(true);
        resultOfMecatorJTextArea.setRows(1);
        resultOfMecatorJTextArea.setTabSize(1);
        resultOfMecatorJTextArea.setWrapStyleWord(true);
        jScrollPane8.setViewportView(resultOfMecatorJTextArea);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Mercator Series.png"))); // NOI18N

        javax.swing.GroupLayout mercatorSeriesJPanelLayout = new javax.swing.GroupLayout(mercatorSeriesJPanel);
        mercatorSeriesJPanel.setLayout(mercatorSeriesJPanelLayout);
        mercatorSeriesJPanelLayout.setHorizontalGroup(
            mercatorSeriesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mercatorSeriesJPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(mercatorSeriesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7)
                    .addGroup(mercatorSeriesJPanelLayout.createSequentialGroup()
                        .addGroup(mercatorSeriesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(verticesJPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mercatorSeriesJPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3)))
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        mercatorSeriesJPanelLayout.setVerticalGroup(
            mercatorSeriesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mercatorSeriesJPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(mercatorSeriesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mercatorSeriesJPanelLayout.createSequentialGroup()
                        .addComponent(verticesJPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        geometriesJTabbedPane.addTab("Mercator Series", mercatorSeriesJPanel);

        fileJMenu.setMnemonic('F');
        fileJMenu.setText("File");

        clearJMenuItem.setMnemonic('C');
        clearJMenuItem.setText("Clear");
        clearJMenuItem.setToolTipText("");
        clearJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJMenuItemActionPerformed(evt);
            }
        });
        fileJMenu.add(clearJMenuItem);

        printJMenuItem.setMnemonic('P');
        printJMenuItem.setText("Print");
        printJMenuItem.setToolTipText("");
        printJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printJMenuItemActionPerformed(evt);
            }
        });
        fileJMenu.add(printJMenuItem);

        printFormJMenuItem.setMnemonic('r');
        printFormJMenuItem.setText("Print Form");
        printFormJMenuItem.setToolTipText("");
        printFormJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printFormJMenuItemActionPerformed(evt);
            }
        });
        fileJMenu.add(printFormJMenuItem);

        exitJMenuItem.setMnemonic('E');
        exitJMenuItem.setText("Exit");
        exitJMenuItem.setToolTipText("");
        exitJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitJMenuItemActionPerformed(evt);
            }
        });
        fileJMenu.add(exitJMenuItem);

        lab6JMenuBar.add(fileJMenu);

        panelJMenu.setMnemonic('P');
        panelJMenu.setText("Panel");

        mainJMenuItem.setMnemonic('M');
        mainJMenuItem.setText("Main Panel");
        mainJMenuItem.setToolTipText("");
        mainJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainJMenuItemActionPerformed(evt);
            }
        });
        panelJMenu.add(mainJMenuItem);

        triangleJMenuItem.setMnemonic('T');
        triangleJMenuItem.setText("Triangle Calculations");
        triangleJMenuItem.setToolTipText("");
        triangleJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                triangleJMenuItemActionPerformed(evt);
            }
        });
        panelJMenu.add(triangleJMenuItem);

        rightTriangleJMenuItem.setMnemonic('R');
        rightTriangleJMenuItem.setText("Right Triangle");
        rightTriangleJMenuItem.setToolTipText("");
        rightTriangleJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightTriangleJMenuItemActionPerformed(evt);
            }
        });
        panelJMenu.add(rightTriangleJMenuItem);

        anyTriangleJMenuItem.setMnemonic('A');
        anyTriangleJMenuItem.setText("Any Triangle");
        anyTriangleJMenuItem.setToolTipText("");
        anyTriangleJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anyTriangleJMenuItemActionPerformed(evt);
            }
        });
        panelJMenu.add(anyTriangleJMenuItem);

        mercatorSeriesJMenuItem.setMnemonic('M');
        mercatorSeriesJMenuItem.setText("Mercator Series");
        mercatorSeriesJMenuItem.setToolTipText("Approximation for ln(x+1)");
        mercatorSeriesJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mercatorSeriesJMenuItemActionPerformed(evt);
            }
        });
        panelJMenu.add(mercatorSeriesJMenuItem);

        lab6JMenuBar.add(panelJMenu);

        helpJMenu.setMnemonic('H');
        helpJMenu.setText("Help");

        aboutJMenuItem.setMnemonic('A');
        aboutJMenuItem.setText("About");
        aboutJMenuItem.setToolTipText("Show the about form");
        aboutJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutJMenuItemActionPerformed(evt);
            }
        });
        helpJMenu.add(aboutJMenuItem);

        lab6JMenuBar.add(helpJMenu);

        setJMenuBar(lab6JMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(geometriesJTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(geometriesJTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method           exitJMenuItemActionPerformed()
     * Description      MenuItem action to exit the application.
     * Date 5/15/2021
     * @param evt 
     * @author          <i>Robert Tang</i>
     * </pre>
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void exitJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitJMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitJMenuItemActionPerformed
    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method           aboutJMenuItemActionPerformed()
     * Description      MenuItem action to displys the about form.
     * Date 5/15/2021
     * @param evt 
     * @author          <i>Robert Tang</i>
     * </pre>
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void aboutJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutJMenuItemActionPerformed
        About instanceAbout = new About(this, true);
        instanceAbout.setVisible(true);
    }//GEN-LAST:event_aboutJMenuItemActionPerformed
    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method           printJMenuItemActionPerformed()
     * Description      MenuItem action to prints the calcluation results of 
     *                  4 panels.
     * Date 5/15/2021
     * @param evt 
     * @author          <i>Robert Tang</i>
     * </pre>
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void printJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printJMenuItemActionPerformed
        try {
            JTextArea result = new JTextArea();
            result.setText(
                    resultJTextArea.getText() + "\n"
                    + resultRightTriangleJTextArea.getText() + "\n"
                    + resultOfAnyTriangleJTextArea.getText() + "\n"
                    + resultOfMecatorJTextArea.getText() + "\n"
            );

            result.print();
        } catch (PrinterException e) {
            JOptionPane.showMessageDialog(this,
                    "Unable to print.",
                    "Print Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_printJMenuItemActionPerformed
    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method           clearJMenuItemActionPerformed()
     * Description      MenuItem action to clears all textfields and testareas.
     * Date 5/15/2021
     * @param evt 
     * @author          <i>Robert Tang</i>
     * </pre>
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void clearJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJMenuItemActionPerformed
        // Clear all textfields and textareas
        this.resultJTextArea.setText("");
        this.resultOfAnyTriangleJTextArea.setText("");
        this.resultOfMecatorJTextArea.setText("");
        this.resultRightTriangleJTextArea.setText("");
        this.x1AnyJFormattedTextField.setText("");
        this.x1JFormattedTextField.setText("");
        this.x2AnyJFormattedTextField.setText("");
        this.x2JFormattedTextField.setText("");
        this.x3AnyJFormattedTextField.setText("");
        this.x3JFormattedTextField.setText("");
        this.xValueJFormattedTextField.setText("");
        this.y1AnyJFormattedTextField.setText("");
        this.y1JFormattedTextField.setText("");
        this.y1TestAnyTriangleJFormattedTextField.setText("");
        this.y2AnyJFormattedTextField.setText("");
        this.y2JFormattedTextField.setText("");
        this.y3AnyJFormattedTextField.setText("");
        this.y3JFormattedTextField.setText("");
        this.yValueJFormattedTextField.setText("");
        this.bJFormattedTextField.setText("");
        this.cJFormattedTextField.setText("");
        this.x1TestAnyTriangleJFormattedTextField.setText("");
        this.numberOfTermsJFormattedTextField.setText("");
        this.value4xJFormattedTextField.setText("");
        this.figureJComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_clearJMenuItemActionPerformed
    
    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method           figureJComboBoxItemStateChanged()
     * Description      Change event for the figure jCombox that change to related panel.
     * Date 5/15/2021
     * @param evt 
     * @author          <i>Robert Tang</i>
     * </pre>
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void figureJComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_figureJComboBoxItemStateChanged
        geometriesJTabbedPane.setSelectedIndex(figureJComboBox.getSelectedIndex());
    }//GEN-LAST:event_figureJComboBoxItemStateChanged
    
    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method           triangleJLabelMouseClicked()
     * Description      Click event for the triangle figure that changes to related panel.
     * Date 5/15/2021
     * @param evt 
     * @author          <i>Robert Tang</i>
     * </pre>
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void triangleJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_triangleJLabelMouseClicked
        geometriesJTabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_triangleJLabelMouseClicked
    
    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method           rightTriangleJLabelMouseClicked()
     * Description      Click event for the right triangle figure that changes to related panel.
     * Date 5/15/2021
     * @param evt 
     * @author          <i>Robert Tang</i>
     * </pre>
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void rightTriangleJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rightTriangleJLabelMouseClicked
        geometriesJTabbedPane.setSelectedIndex(2);
    }//GEN-LAST:event_rightTriangleJLabelMouseClicked
    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method           anyTriangleJLabelMouseClicked()
     * Description      Click event for the any triangle figure that changes to related panel.
     * Date 5/15/2021
     * @param evt 
     * @author          <i>Robert Tang</i>
     * </pre>
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void anyTriangleJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anyTriangleJLabelMouseClicked
        geometriesJTabbedPane.setSelectedIndex(3);
    }//GEN-LAST:event_anyTriangleJLabelMouseClicked
    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method           anyTriangleJLabelMouseClicked()
     * Description      Click event for the mercator series figure that changes to related panel.
     * Date 5/15/2021
     * @param evt 
     * @author          <i>Robert Tang</i>
     * </pre>
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void mercatorSeriesJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mercatorSeriesJLabelMouseClicked
        geometriesJTabbedPane.setSelectedIndex(4);
    }//GEN-LAST:event_mercatorSeriesJLabelMouseClicked
    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method           mainJMenuItemActionPerformed()
     * Description      MenuItem action for changing to main panel.
     * Date 5/15/2021
     * @param evt 
     * @author          <i>Robert Tang</i>
     * </pre>
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void mainJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainJMenuItemActionPerformed
        geometriesJTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_mainJMenuItemActionPerformed
    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method           triangleJMenuItemActionPerformed()
     * Description      MenuItem action for changing to triangle panel.
     * Date 5/15/2021
     * @param evt 
     * @author          <i>Robert Tang</i>
     * </pre>
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void triangleJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_triangleJMenuItemActionPerformed
        geometriesJTabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_triangleJMenuItemActionPerformed
    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method           rightTriangleJMenuItemActionPerformed()
     * Description      MenuItem action for changing to the right triangle panel.
     * Date 5/15/2021
     * @param evt 
     * @author          <i>Robert Tang</i>
     * </pre>
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void rightTriangleJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightTriangleJMenuItemActionPerformed
        geometriesJTabbedPane.setSelectedIndex(2);
    }//GEN-LAST:event_rightTriangleJMenuItemActionPerformed
    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method           mercatorSeriesJMenuItemActionPerformed()
     * Description      MenuItem action for changing to the mercator series panel.
     * Date 5/15/2021
     * @param evt 
     * @author          <i>Robert Tang</i>
     * </pre>
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void mercatorSeriesJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mercatorSeriesJMenuItemActionPerformed
        geometriesJTabbedPane.setSelectedIndex(4);
    }//GEN-LAST:event_mercatorSeriesJMenuItemActionPerformed
    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method           anyTriangleJMenuItemActionPerformed()
     * Description      MenuItem action for changing to the any-triangle panel.
     * Date 5/15/2021
     * @param evt 
     * @author          <i>Robert Tang</i>
     * </pre>
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void anyTriangleJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anyTriangleJMenuItemActionPerformed
        geometriesJTabbedPane.setSelectedIndex(3);
    }//GEN-LAST:event_anyTriangleJMenuItemActionPerformed
    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method           calculationJPanelComponentShown()
     * Description      Set default button when the main panel is shown.
     * Date 5/15/2021
     * @param evt 
     * @author          <i>Robert Tang</i>
     * </pre>
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void calculationJPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_calculationJPanelComponentShown
        this.getRootPane().setDefaultButton(triangleJButton);
        x1JFormattedTextField.requestFocus();
        descTriangleJTextArea.setCaretPosition(0);
    }//GEN-LAST:event_calculationJPanelComponentShown
    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method           rightTriangleJPanelComponentShown()
     * Description      Set default button when the right triangle panel is shown.
     * Date 5/15/2021
     * @param evt 
     * @author          <i>Robert Tang</i>
     * </pre>
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void rightTriangleJPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_rightTriangleJPanelComponentShown
        this.getRootPane().setDefaultButton(rightTriJButton);
        bJFormattedTextField.requestFocus();
        descRightTriangleJTextArea.setCaretPosition(0);
    }//GEN-LAST:event_rightTriangleJPanelComponentShown
    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method           anyTriangleJPanelComponentShown()
     * Description      Set default button when the any triangle panel is shown.
     * Date 5/15/2021
     * @param evt 
     * @author          <i>Robert Tang</i>
     * </pre>
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void anyTriangleJPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_anyTriangleJPanelComponentShown
        this.getRootPane().setDefaultButton(anyTriangleJButton);
        x1AnyJFormattedTextField.requestFocus();
    }//GEN-LAST:event_anyTriangleJPanelComponentShown
    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method           mercatorSeriesJPanelComponentShown()
     * Description      Set default button when the mercator series panel is shown.
     * Date 5/15/2021
     * @param evt 
     * @author          <i>Robert Tang</i>
     * </pre>
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void mercatorSeriesJPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_mercatorSeriesJPanelComponentShown
        this.getRootPane().setDefaultButton(mercatorJButton);
        numberOfTermsJFormattedTextField.requestFocus();
    }//GEN-LAST:event_mercatorSeriesJPanelComponentShown
    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method           triangleJButtonActionPerformed()
     * Description      Button action for calculating a triangle's area, perimeter.
     * Date 5/15/2021
     * @param evt 
     * @author          <i>Robert Tang</i>
     * </pre>
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void triangleJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_triangleJButtonActionPerformed
        double vx1, vx2, vx3;
        double vy1, vy2, vy3;
        double side1, side2, side3;
        double perimeter, area, semiperimeter;
        boolean isGoodTriangle = false;

        try {
            if(x1JFormattedTextField.getText().trim().length()<1){
                JOptionPane.showMessageDialog(this, "Please enter a value for x1.", "Input Error", JOptionPane.WARNING_MESSAGE);
                x1JFormattedTextField.requestFocus();
            }
            else if(y1JFormattedTextField.getText().trim().length()<1){
                JOptionPane.showMessageDialog(this, "Please enter a value for y1.", "Input Error", JOptionPane.WARNING_MESSAGE);
                y1JFormattedTextField.requestFocus();
            }
            else if(x2JFormattedTextField.getText().trim().length()<1){
                JOptionPane.showMessageDialog(this, "Please enter a value for x2.", "Input Error", JOptionPane.WARNING_MESSAGE);
                x2JFormattedTextField.requestFocus();
            }
            else if(y2JFormattedTextField.getText().trim().length()<1){
                JOptionPane.showMessageDialog(this, "Please enter a value for y2.", "Input Error", JOptionPane.WARNING_MESSAGE);
                y2JFormattedTextField.requestFocus();
            }
            else if(x3JFormattedTextField.getText().trim().length()<1){
                JOptionPane.showMessageDialog(this, "Please enter a value for x3.", "Input Error", JOptionPane.WARNING_MESSAGE);
                x3JFormattedTextField.requestFocus();
            }
            else if(y3JFormattedTextField.getText().trim().length()<1){
                JOptionPane.showMessageDialog(this, "Please enter a value for y3.", "Input Error", JOptionPane.WARNING_MESSAGE);
                y3JFormattedTextField.requestFocus();
            }
            else
            {
                vx1 = Double.parseDouble(x1JFormattedTextField.getText());
                vx2 = Double.parseDouble(x2JFormattedTextField.getText());
                vx3 = Double.parseDouble(x3JFormattedTextField.getText());
                vy1 = Double.parseDouble(y1JFormattedTextField.getText());
                vy2 = Double.parseDouble(y2JFormattedTextField.getText());
                vy3 = Double.parseDouble(y3JFormattedTextField.getText());

                Triangle myTrig = new Triangle(vx1, vy1, vx2, vy2, vx3, vy3);
                side1 = myTrig.distance(vx1, vy1, vx2, vy2);
                side2 = myTrig.distance(vx1, vy1, vx3, vy3);
                side3 = myTrig.distance(vx2, vy2, vx3, vy3);
                
                perimeter = myTrig.getPerimeter();
                semiperimeter = perimeter / 2;
                area = myTrig.getArea();

                if (area > 0) {
                    resultJTextArea.setText(
                            myTrig.padSpaces("x", "y")
                            + myTrig.padSpaces(String.valueOf(vx1), String.valueOf(vy1))
                            + myTrig.padSpaces(String.valueOf(vx2), String.valueOf(vy2))
                            + myTrig.padSpaces(String.valueOf(vx3), String.valueOf(vy3))
                            + "Triangle with above vertices has perimeter: " + numFormat.format(perimeter)
                            + " and area: " + numFormat.format(area)
                    );
                }else{    
                    resultJTextArea.setText("It's not a valide triangle!");
                }// end if
            }// end if
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Not a valid input.", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_triangleJButtonActionPerformed
    
    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method           rightTriJButtonActionPerformed()
     * Description      Button action for calculating a right triangle's area, perimeter.
     * Date 5/15/2021
     * @param evt 
     * @author          <i>Robert Tang</i>
     * </pre>
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void rightTriJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightTriJButtonActionPerformed
        double vx1 = 0, vy1 = 0;
        double vxb = 0, vyb;
        double vxc, vyc = 0;
        double px, py;
        double side1, side2, side3;
        double perimeter, area, semiperimeter;
        boolean isGoodTriangle = false;

        try {
            if (bJFormattedTextField.getText().trim().length() < 1) {
                JOptionPane.showMessageDialog(this, "Please enter a value for B.", "Input Error", JOptionPane.WARNING_MESSAGE);
                bJFormattedTextField.requestFocus();
            } else if (cJFormattedTextField.getText().trim().length() < 1) {
                JOptionPane.showMessageDialog(this, "Please enter a value for C.", "Input Error", JOptionPane.WARNING_MESSAGE);
                cJFormattedTextField.requestFocus();
            } else if (xValueJFormattedTextField.getText().trim().length() < 1) {
                JOptionPane.showMessageDialog(this, "Please enter a value for X.", "Input Error", JOptionPane.WARNING_MESSAGE);
                xValueJFormattedTextField.requestFocus();
            } else if (yValueJFormattedTextField.getText().trim().length() < 1) {
                JOptionPane.showMessageDialog(this, "Please enter a value for Y.", "Input Error", JOptionPane.WARNING_MESSAGE);
                yValueJFormattedTextField.requestFocus();
            } else {
                vyb = Double.parseDouble(bJFormattedTextField.getText());
                vxc = Double.parseDouble(cJFormattedTextField.getText());
                px = Double.parseDouble(xValueJFormattedTextField.getText());
                py = Double.parseDouble(yValueJFormattedTextField.getText());

                Triangle myTrig = new Triangle(vx1, vy1, vxb, vyb, vxc, vyc);
                side1 = myTrig.distance(vx1, vy1, vxb, vyb);
                side2 = myTrig.distance(vx1, vy1, vxc, vyc);
                side3 = myTrig.distance(vxb, vyb, vxc, vyc);
                
                area = myTrig.getArea();
                if (area >0) {
                    perimeter = myTrig.getPerimeter();
                    semiperimeter = perimeter / 2;
                    
                    String pointStatus = ((px <= vxc && px >= 0) && (py <= vyb && py >= 0)) ? "inside" : "outside";
                    resultRightTriangleJTextArea.setText(
                        myTrig.padSpaces("x", "y")
                        + myTrig.padSpaces(String.valueOf(vx1), String.valueOf(vy1))
                        + myTrig.padSpaces(String.valueOf(vxb), String.valueOf(vyb))
                        + myTrig.padSpaces(String.valueOf(vxc), String.valueOf(vyc))
                        + "\n"
                        + "Triangle with above vertices has "
                        + "perimeter " + numFormat.format(perimeter)
                        + " and area " + numFormat.format(area) + ".\n\n"
                        + "The point (" + px + "," + py + ") is " + pointStatus + " the triangle.\n"
                    );
                }else{    
                    resultRightTriangleJTextArea.setText("It's not a valide triangle!");
                }// end if
            }// end if
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_rightTriJButtonActionPerformed
    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method           anyTriangleJButtonActionPerformed()
     * Description      Button action for calculating any types of triangle's area, perimeter.
     * Date 5/15/2021
     * @param evt 
     * @author          <i>Robert Tang</i>
     * </pre>
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void anyTriangleJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anyTriangleJButtonActionPerformed
        double vx1, vy1;
        double vx2, vy2;
        double vx3, vy3;
        double px, py;
        double side1, side2, side3;
        double perimeter, area;

        try {
            if (x1AnyJFormattedTextField.getText().trim().length() < 1) {
                JOptionPane.showMessageDialog(this, "Please enter a value for X1.", "Input Error", JOptionPane.WARNING_MESSAGE);
                x1AnyJFormattedTextField.requestFocus();
            } else if (y1AnyJFormattedTextField.getText().trim().length() < 1) {
                JOptionPane.showMessageDialog(this, "Please enter a value for Y1.", "Input Error", JOptionPane.WARNING_MESSAGE);
                y1AnyJFormattedTextField.requestFocus();
            } else if (x2AnyJFormattedTextField.getText().trim().length() < 1) {
                JOptionPane.showMessageDialog(this, "Please enter a value for X2.", "Input Error", JOptionPane.WARNING_MESSAGE);
                x2AnyJFormattedTextField.requestFocus();
            } else if (y2AnyJFormattedTextField.getText().trim().length() < 1) {
                JOptionPane.showMessageDialog(this, "Please enter a value for Y2.", "Input Error", JOptionPane.WARNING_MESSAGE);
                y2AnyJFormattedTextField.requestFocus();
            } else if (x3AnyJFormattedTextField.getText().trim().length() < 1) {
                JOptionPane.showMessageDialog(this, "Please enter a value for X3.", "Input Error", JOptionPane.WARNING_MESSAGE);
                x3AnyJFormattedTextField.requestFocus();
            } else if (y3AnyJFormattedTextField.getText().trim().length() < 1) {
                JOptionPane.showMessageDialog(this, "Please enter a value for Y3.", "Input Error", JOptionPane.WARNING_MESSAGE);
                y3AnyJFormattedTextField.requestFocus();
            } else if (x1TestAnyTriangleJFormattedTextField.getText().trim().length() < 1) {
                JOptionPane.showMessageDialog(this, "Please enter a value for x.", "Input Error", JOptionPane.WARNING_MESSAGE);
                x1TestAnyTriangleJFormattedTextField.requestFocus();
            } else if (y1TestAnyTriangleJFormattedTextField.getText().trim().length() < 1) {
                JOptionPane.showMessageDialog(this, "Please enter a value for y.", "Input Error", JOptionPane.WARNING_MESSAGE);
                y1TestAnyTriangleJFormattedTextField.requestFocus();
            } else {
                vx1 = Double.parseDouble(x1AnyJFormattedTextField.getText());
                vy1 = Double.parseDouble(y1AnyJFormattedTextField.getText());
                vx2 = Double.parseDouble(x2AnyJFormattedTextField.getText());
                vy2 = Double.parseDouble(y2AnyJFormattedTextField.getText());
                vx3 = Double.parseDouble(x3AnyJFormattedTextField.getText());
                vy3 = Double.parseDouble(y3AnyJFormattedTextField.getText());
                px = Double.parseDouble(x1TestAnyTriangleJFormattedTextField.getText());
                py = Double.parseDouble(y1TestAnyTriangleJFormattedTextField.getText());

                Triangle myTrig = new Triangle(vx1, vy1, vx2, vy2, vx3, vy3);
                side1 = myTrig.distance(vx1, vy1, vx2, vy2);
                side2 = myTrig.distance(vx1, vy1, vx3, vy3);
                side3 = myTrig.distance(vx1, vy1, vx3, vy3);
                area = myTrig.getArea();
                if (area >0) {
                    perimeter = myTrig.getPerimeter();
                    double area1 = myTrig.getArea(px, py, vx2, vy2, vx3, vy3);
                    double area2 = myTrig.getArea(vx1, vy1, px, py, vx3, vy3);
                    double area3 = myTrig.getArea(vx1, vy1, vx2, vy2, px, py);
                    String pointStatus = (Math.abs(area - (area1 + area2 + area3)) < 0.000001d) ? "inside" : "outside";
                    resultOfAnyTriangleJTextArea.setText(
                        "Point (" + px + "," + py + ") is " + pointStatus + " the triangle.\n\n"
                        + "The perimeter of the triangle is " + numFormat.format(perimeter) + "\n\n"
                        + "The area of the triangle is " + numFormat.format(area)
                    );
                } else {
                    resultOfAnyTriangleJTextArea.setText("It's not a valide triangle.");
                }
            }
        } catch (HeadlessException | NumberFormatException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_anyTriangleJButtonActionPerformed
    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method           mercatorJButtonActionPerformed()
     * Description      Button action for calculating the mercator series.
     * Date 5/15/2021
     * @param evt 
     * @author          <i>Robert Tang</i>
     * </pre>
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void mercatorJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mercatorJButtonActionPerformed
        double sumForward = 0.0, trueValue, argument;
        long numberOfTerms, startTime, endTime, elpasedTimeForward;
        int MAX = 10;

        try {
            if (numberOfTermsJFormattedTextField.getText().trim().length() < 1) {
                JOptionPane.showMessageDialog(this, "Please enter a value for number of term.", "Input Error", JOptionPane.WARNING_MESSAGE);
                numberOfTermsJFormattedTextField.requestFocus();
            } else if (value4xJFormattedTextField.getText().trim().length() < 1) {
                JOptionPane.showMessageDialog(this, "Please enter a value for x.", "Input Error", JOptionPane.WARNING_MESSAGE);
                value4xJFormattedTextField.requestFocus();
            }
            else{
                numberOfTerms = Integer.parseInt(numberOfTermsJFormattedTextField.getText());
                argument = Double.parseDouble(value4xJFormattedTextField.getText());
                
                if(numberOfTerms < 1){
                    JOptionPane.showMessageDialog(this, "Number of term cannot less than 1.", "Input Error", JOptionPane.WARNING_MESSAGE);
                    numberOfTermsJFormattedTextField.requestFocus();
                }
                else if(argument < 0 || argument >= MAX){
                    JOptionPane.showMessageDialog(this, "Value of x cannot less than 0 or greater than "+MAX+".", "Input Error", JOptionPane.WARNING_MESSAGE);
                    value4xJFormattedTextField.requestFocus();
                }
                else{
                    trueValue = Math.log(argument+1.0);

                    // records time spent for repeating calculation
                    startTime = System.currentTimeMillis();
                    for (int n = 1; n <= numberOfTerms; n++) {
                        sumForward += (Math.pow(-1.0, n+1) / n) * Math.pow(argument, n);
                    }
                    endTime = System.currentTimeMillis();
                    elpasedTimeForward = endTime - startTime;

                    if(sumForward != Double.NaN){
                        resultOfMecatorJTextArea.setText(
                            "The sum of the Mercator series added forward is "+sumForward+
                            " and it took: " +elpasedTimeForward+ " milliseconds. \n\n"+
                            "The true value of ln("+(1 + argument)+") = "+trueValue+"\n\n"+
                            "The relative error of the Mercator series with "+numberOfTerms+
                            " terms is "+ (100 * Math.abs(sumForward-trueValue) + 1) + "%"
                        );
                    }
                    else{
                        resultOfMecatorJTextArea.setText(
                            "The sum of the Mercator series cannot be determined "+
                            "accurately and it took: " +elpasedTimeForward+ " milliseconds. \n\n"+
                            "The true value of ln("+(1 + argument)+") = "+trueValue+"\n\n"+
                            "The relative error of the Mercator series with "+numberOfTerms+
                            " terms is "+ (100 * Math.abs(sumForward-trueValue) + 1) + "%"
                        );
                    }
                }
            }
        } catch (NumberFormatException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_mercatorJButtonActionPerformed
    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method           printFormJMenuItemActionPerformed()
     * Description      MenuItem action to print the form.
     * Date 5/15/2021
     * @param evt 
     * @author          <i>Robert Tang</i>
     * </pre>
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    private void printFormJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printFormJMenuItemActionPerformed
        PrintUtilities.printComponent(this);
    }//GEN-LAST:event_printFormJMenuItemActionPerformed
    
    /**
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     * <pre>
     * Method           main()
     * Description      main method of the geometries GUI.
     * Date 5/15/2021
     *  @param args the command line arguments
     * @author          <i>Robert Tang</i>
     * </pre>
     * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeometriesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeometriesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeometriesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeometriesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        Splash instanceOfSplash = new Splash(2000);
        instanceOfSplash.showSplash();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeometriesGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutJMenuItem;
    private javax.swing.JButton anyTriangleJButton;
    private javax.swing.JLabel anyTriangleJLabel;
    private javax.swing.JMenuItem anyTriangleJMenuItem;
    private javax.swing.JPanel anyTriangleJPanel;
    private javax.swing.JFormattedTextField bJFormattedTextField;
    private javax.swing.JLabel bJLabel;
    private javax.swing.JFormattedTextField cJFormattedTextField;
    private javax.swing.JLabel cJLabel;
    private javax.swing.JPanel calculationJPanel;
    private javax.swing.JMenuItem clearJMenuItem;
    private javax.swing.JTextArea descAnyTriJTextArea;
    private javax.swing.JTextArea descMercatorJTextArea;
    private javax.swing.JTextArea descRightTriangleJTextArea;
    private javax.swing.JTextArea descTriangleJTextArea;
    private javax.swing.JMenuItem exitJMenuItem;
    private javax.swing.JComboBox<String> figureJComboBox;
    private javax.swing.JMenu fileJMenu;
    private javax.swing.JTabbedPane geometriesJTabbedPane;
    private javax.swing.JMenu helpJMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JMenuBar lab6JMenuBar;
    private javax.swing.JMenuItem mainJMenuItem;
    private javax.swing.JPanel mainJPanel;
    private javax.swing.JButton mercatorJButton;
    private javax.swing.JLabel mercatorSeriesJLabel;
    private javax.swing.JMenuItem mercatorSeriesJMenuItem;
    private javax.swing.JPanel mercatorSeriesJPanel;
    private javax.swing.JFormattedTextField numberOfTermsJFormattedTextField;
    private javax.swing.JLabel numbersOfTermsJLabel;
    private javax.swing.JMenu panelJMenu;
    private javax.swing.JPanel pointsJPanel;
    private javax.swing.JMenuItem printFormJMenuItem;
    private javax.swing.JMenuItem printJMenuItem;
    private javax.swing.JTextArea resultJTextArea;
    private javax.swing.JTextArea resultOfAnyTriangleJTextArea;
    private javax.swing.JTextArea resultOfMecatorJTextArea;
    private javax.swing.JTextArea resultRightTriangleJTextArea;
    private javax.swing.JButton rightTriJButton;
    private javax.swing.JLabel rightTriangleJLabel;
    private javax.swing.JMenuItem rightTriangleJMenuItem;
    private javax.swing.JPanel rightTriangleJPanel;
    private javax.swing.JButton triangleJButton;
    private javax.swing.JLabel triangleJLabel;
    private javax.swing.JMenuItem triangleJMenuItem;
    private javax.swing.JFormattedTextField value4xJFormattedTextField;
    private javax.swing.JLabel value4xJLabel;
    private javax.swing.JPanel verticesJPanel;
    private javax.swing.JPanel verticesJPanel2;
    private javax.swing.JPanel verticesJPanel3;
    private javax.swing.JFormattedTextField x1AnyJFormattedTextField;
    private javax.swing.JLabel x1AnyJLabel;
    private javax.swing.JFormattedTextField x1JFormattedTextField;
    private javax.swing.JLabel x1JLabel;
    private javax.swing.JLabel x1JLabel4;
    private javax.swing.JFormattedTextField x1TestAnyTriangleJFormattedTextField;
    private javax.swing.JFormattedTextField x2AnyJFormattedTextField;
    private javax.swing.JLabel x2AnyJLabel;
    private javax.swing.JFormattedTextField x2JFormattedTextField;
    private javax.swing.JLabel x2JLabel;
    private javax.swing.JFormattedTextField x3AnyJFormattedTextField;
    private javax.swing.JLabel x3AnyJLabel;
    private javax.swing.JFormattedTextField x3JFormattedTextField;
    private javax.swing.JLabel x3JLabel;
    private javax.swing.JFormattedTextField xValueJFormattedTextField;
    private javax.swing.JLabel xValueJLabel;
    private javax.swing.JFormattedTextField y1AnyJFormattedTextField;
    private javax.swing.JLabel y1AnyJLabel;
    private javax.swing.JFormattedTextField y1JFormattedTextField;
    private javax.swing.JLabel y1JLabel;
    private javax.swing.JLabel y1JLabel4;
    private javax.swing.JFormattedTextField y1TestAnyTriangleJFormattedTextField;
    private javax.swing.JFormattedTextField y2AnyJFormattedTextField;
    private javax.swing.JLabel y2AnyJLabel;
    private javax.swing.JFormattedTextField y2JFormattedTextField;
    private javax.swing.JLabel y2JLabel;
    private javax.swing.JFormattedTextField y3AnyJFormattedTextField;
    private javax.swing.JLabel y3AnyJLabel;
    private javax.swing.JFormattedTextField y3JFormattedTextField;
    private javax.swing.JLabel y3JLabel;
    private javax.swing.JFormattedTextField yValueJFormattedTextField;
    private javax.swing.JLabel yValueJLabel;
    // End of variables declaration//GEN-END:variables
}
